### ISSUE TITLE
Fixing binding bug and aftermath

### ISSUE THREAD

**Issue by yossigil** [yossigil/safot#414]
There was a bug in the implementation of bind, which made it throw the wrong errors. Fixing this bug, caused may exceptions to fail.

**Comment by DorYeheskel** [comment]
@yossigil 
I already fixed it, during my implantations of evaluation.

This is the C implementation:
```lisp
  if (names.null() && !values.null()) names.error(MISSING);
  if (!names.null() && values.null()) values.error(MISSING);
  if (names.null())
    return values.null() ?  alist : values.error(REDUNDANT);
  return names.car().cons(values.car()).cons(bind(names.cdr(), values.cdr(), alist));
```

By the way,  I just finished to test the Lisp implementation of Bind (from the book), and it works great + give the expected errors.

**Comment by DorYeheskel** [comment]
@yossigil 
Fixed.

**Comment by yossigil** [comment]
Some of the cases failed because names were incorrect, e.g., `S c("b"), y("x");` You fixed this by using new names, but this did not really fix the bug

**Comment by DorYeheskel** [comment]
Because of the fact that the a-list is not freed, some of the tests are dependent.
The solution is to free the a-list for each test in all of our 300 tests, but because only few tests failed which used some specific names, I think it is ok for now.

**Comment by yossigil** [comment]
There are two kinds of failures: bugs, such as `c("b")` and interdependent tests. However, tests should be oblivious to the current value of the alist, e.g., by using a different name each time they run. Will see what I can do.

**Comment by yossigil** [comment]
We need to revise this

**Comment by yossigil** [comment]
There is a need for a global checkup: compile somehow a list of throws, and make sure that they are right. Again, in a design session.
